/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f58b3bbf-cf10-44ee-9c10-d917375a5d16",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kTYNaJdTL",
    "aws_user_pools_web_client_id": "5c48pjcuo6174149ttujm0fmj1",
    "oauth": {}
};


export default awsmobile;
